# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('duration', models.IntegerField()),
                ('country', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=100)),
                ('release', models.DateField()),
                ('producers', models.TextField(max_length=400)),
                ('description', models.TextField()),
                ('img', models.TextField()),
                ('actors', models.ManyToManyField(related_name='film', to='apprest.Actor')),
                ('directors', models.ManyToManyField(related_name='film', to='apprest.Director')),
            ],
        ),
        migrations.CreateModel(
            name='FilmActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Film')),
            ],
        ),
        migrations.CreateModel(
            name='FilmDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Director')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Film')),
            ],
        ),
    ]
