# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=100)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('producer', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=100)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Director')),
            ],
        ),
    ]
