# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmactors',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='filmactors',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmdirectors',
            name='director',
        ),
        migrations.RemoveField(
            model_name='filmdirectors',
            name='film',
        ),
        migrations.DeleteModel(
            name='FilmActors',
        ),
        migrations.DeleteModel(
            name='FilmDirectors',
        ),
    ]
