# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0002_film_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FilmActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='FilmDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Director')),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='filmdirectors',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Film'),
        ),
        migrations.AddField(
            model_name='filmactors',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.Film'),
        ),
    ]
