# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0003_auto_20160607_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.TextField(max_length=400),
        ),
    ]
