# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0004_auto_20160607_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
