# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0005_auto_20160607_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.DateField(),
        ),
    ]
